apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata:
  name: ap-northeast-2c # Pod 전용 서브넷 #2의 Availability Zone 기호 (필요시 업데이트)
spec:
  securityGroups:
    - sg-01aaefdba80cd887b # Cluster Security Group ID ([작업 2] 수행시의 Terraform Output 참조)
  subnet: subnet-044214692de7fb903 # Pod 전용 서브넷 #2의 서브넷 ID (기 생성되어 있는 서브넷의 ID)
